-- 1. Create the Users Table
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  name TEXT,
  role TEXT NOT NULL DEFAULT 'teacher',
  sub_district TEXT
);

-- 2. Insert the Initial Admin User
INSERT INTO users (username, password, name, role)
VALUES ('admin', 'admin123', 'System Administrator', 'admin')
ON CONFLICT (username) DO NOTHING;

-- 3. (Optional) Insert a Default Teacher for testing
INSERT INTO users (username, password, name, role)
VALUES ('teacher', 'teacher123', 'Default Teacher', 'teacher')
ON CONFLICT (username) DO NOTHING;

-- 4. Create Downloads Table
CREATE TABLE IF NOT EXISTS downloads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  file_url TEXT NOT NULL,
  category TEXT DEFAULT 'General',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Create Gallery Table
CREATE TABLE IF NOT EXISTS gallery (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  image_url TEXT NOT NULL,
  caption TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Enable Row Level Security (RLS) - Optional for basic setup but recommended
-- ALTER TABLE downloads ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE gallery ENABLE ROW LEVEL SECURITY;

-- 7. Policies (If RLS is enabled)
-- CREATE POLICY "Public can view downloads" ON downloads FOR SELECT USING (true);
-- CREATE POLICY "Admins can insert downloads" ON downloads FOR INSERT WITH CHECK (true); -- Ideally restrict to auth users
-- CREATE POLICY "Public can view gallery" ON gallery FOR SELECT USING (true);
-- CREATE POLICY "Admins can insert gallery" ON gallery FOR INSERT WITH CHECK (true);
