-- 1. Create the Users Table
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  name TEXT,
  role TEXT NOT NULL DEFAULT 'teacher'
);

-- 2. Insert the Initial Admin User
INSERT INTO users (username, password, name, role)
VALUES ('admin', 'admin123', 'System Administrator', 'admin');

-- 3. (Optional) Insert a Default Teacher for testing
INSERT INTO users (username, password, name, role)
VALUES ('teacher', 'teacher123', 'Default Teacher', 'teacher');
